name: Build wheels

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:

  build:

    runs-on: ${{ matrix.os }}
    outputs:
      VERSION: ${{ steps.build_wheel.outputs.version }}
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Build wheel
        id: build_wheel
        shell: bash
        run: |
          pip wheel . -v -w wheelhouse
          pip install toml
          VERSION="$(python -c 'import toml; print(toml.load("pyproject.toml")["project"]["version"])')"
          echo "version=${VERSION}" | tee -a $GITHUB_OUTPUT

      - name: Copy wheel
        shell: bash
        run: |
          mkdir -p ${{ github.sha }}
          mv wheelhouse/triton*.whl ${{ github.sha }}/

      - name: Upload an artifact
        uses: actions/upload-artifact@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          if-no-files-found: error
          name: build_artifact
          path: ${{ github.sha }}

  upload-tarballs:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    needs: [ build ]

    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build_artifact
          path: dist

      - name: Set up a release page
        id: setup_release
        run: |
          TRITONPP_VERSION=${{ needs.build.outputs.version }}
          tag_name="$TRITONPP_VERSION"
          release_title="triton-pp $TRITONPP_VERSION"
          echo "triton-pp $TRITONPP_VERSION created at $(date)" > body.md
          echo "tag_name=$TRITONPP_VERSION" >> $GITHUB_OUTPUT
          echo "release_title=triton-pp-$TRITONPP_VERSION" >> $GITHUB_OUTPUT

      - name: Upload tarballs
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "dist/triton_pp*.whl"
          bodyFile: body.md
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ steps.setup_release.outputs.tag_name }}"
          name: "${{ steps.setup_release.outputs.release_title }}"
          removeArtifacts: false
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true

      - name: Release current commit
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "dist/triton_pp*.whl"
          bodyFile: body.md
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "latest"
          name: "latest"
          removeArtifacts: false
          allowUpdates: true
          replacesArtifacts: true

      - name: Release current commit
        uses: ncipollo/release-action@v1.12.0
        with:
          owner: makslevental
          repo: wheels
          artifacts: "dist/*.whl"
          token: "${{ secrets.WHEELS_REPO }}"
          tag: "i"
          name: "i"
          removeArtifacts: false
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
