name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:

  test-x86:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-22.04,
#          macos-11,
          windows-2022
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install
        shell: bash
        run: |
          pip install setuptools -U
          pip install -e .[test] \
            -f https://github.com/makslevental/triton/releases/expanded_assets/2.1.0 \
            -f https://github.com/makslevental/mlir-python-utils/releases/expanded_assets/latest \
            -f https://github.com/makslevental/mlir-wheels/releases/expanded_assets/latest
          if [ ${{ matrix.os }} == 'windows-2022' ]; then
            # configure-mlir-python-utils.exe -y triton_mlir_bindings
            pushd /tmp && python -m mlir_utils._configuration -y triton_mlir_bindings && popd
          else
            configure-mlir-python-utils -y triton_mlir_bindings
          fi

      - name: Test
        shell: bash
        run: |
          pytest tests
