name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:

  test-x86:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install FileCheck
        run: |
          sudo apt-get update
          sudo apt install llvm-15-tools

      - name: Install
        run: |
          export PIP_EXTRA_INDEX_URL=https://github.com/makslevental/triton/releases/expanded_assets/2.1.0
          pip install -e .[test]

      - name: Test
        run: |
          export FILECHECK=$(which FileCheck-15)
          pytest tests
