name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:

  test:

    runs-on: ${{ matrix.os }}
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-22.04,
          macos-latest,
          windows-2022
        ]
        python_version: [ "3.10", "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install
        shell: bash
        run: |
          pip install setuptools -U
          pip install .[test] -f https://makslevental.github.io/wheels/
          if [ ${{ matrix.os }} == 'windows-2022' ]; then
            # configure-mlir-python-utils.exe -y triton_mlir_bindings
            pushd /tmp && python -m mlir_utils._configuration -y triton_mlir_bindings && popd
          else
            configure-mlir-python-utils -y triton_mlir_bindings
          fi

      - name: Test
        shell: bash
        run: |
          if [ ${{ matrix.os }} == 'windows-2022' ]; then
            pytest -s --ignore-glob=*test_runtime* tests
          else
            pytest -s tests
          fi
